remote_theme: jekyll/minima           # pulls Minima v3 straight from GitHub
plugins:
  - jekyll-remote-theme

title: "Ben Lamb, PhD"
subtitle: "Assistant Professor · Secure Systems & Software Architecture"
description: >
  Minimalist portfolio, writings, and project links.
  Built with dark-mode-ready Minima.

minima:
  skin: dark        # use 'auto' to follow visitor preference
  social_links:
    - { platform: github,  user_url: "https://github.com/benjaminmlamb" }
